# Generated by Django 5.0.6 on 2024-06-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Organizador'), (3, 'Usuario')], default=3, verbose_name='Rol'),
        ),
    ]
